name: Build wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust (Linux and macOS)
        if: runner.os != 'Windows'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
        shell: bash

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel
        run: |
          pwd
          cd python/delta-kernel-python
          maturin build --release
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: python/delta-kernel-python/target/wheels/*.whl
